apiVersion: v1
kind: Pod
metadata:
  name: fssbendpod
  labels:
    app: greet
    tier: backend
spec:
  containers:
    - name: fssbendps
      image: exbackend:v1
      ports:
      - containerPort: 3306
      env:
      - name: MYSQL_ROOT_PASSWORD
        value: root
      - name: MYSQL_DATABASE
        value: demob3db