spring:
  cloud:
    gateway:
      routes:
        - id: serviceA
          uri: lb://serviceA
          predicates:
            - Path=/api/servicea/**








#Example for Gateway Routing
#        - id: serviceA
#          uri: http://localhost:8081
#          predicates:
#            - Path=/api/servicea/**

#        - id: serviceB
#          uri: http://localhost:8082
#          predicates:
#            - Path=/api/serviceb/**