apiVersion: v1
kind: Service
metadata: 
  name: fssfendsvc
  labels:
    app: greet
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 8081
  selector:
    app: greet
    tier: frontend
